### PR TITLE
Exercise 3: Operations

### PR DESCRIPTION
**Pull request by Ulaize**

### CODE REVIEW

**Comment by ziad-saab** [comment]
@Ulaize this code works 100% but you missed one requirement of the exercise. You have to send an error to the user using `res.sendStatus` if they provide you with an invalid operator! Please fix.

**Comment by Ulaize** [comment]
@ziad-saab OOOpppsss.. I got too excited. I will fix it now. Thank you.

**Comment by Ulaize** [comment]
@ziad-saab that seems to work. Let me know :) Thanks.

**Comment by ziad-saab** [comment]
@Ulaize 100%!!!!

**Pull request closed without merging**
