### PR TITLE
Exercise 3: Operations

### PR DESCRIPTION
**Pull request by karlysun**

### CODE REVIEW

**Comment by ziad-saab** [comment]
@karlysun tiny problem. If you send a 400 to the user, then the code does not finish. you need to find a way to exit your function after sending that 400, otherwise the rest of the code will still run.

**Comment by karlysun** [comment]
Am I missing a break?

**Comment by ziad-saab** [comment]
break will only break out of the switch. yoh need to break out of the
function

**Comment by karlysun** [comment]
Added a return in the function

**Pull request closed without merging**
